def getProtienCodes():
    protienCodes = """UUU F      CUU L      AUU I      GUU V
    UUC F      CUC L      AUC I      GUC V
    UUA L      CUA L      AUA I      GUA V
    UUG L      CUG L      AUG M      GUG V
    UCU S      CCU P      ACU T      GCU A
    UCC S      CCC P      ACC T      GCC A
    UCA S      CCA P      ACA T      GCA A
    UCG S      CCG P      ACG T      GCG A
    UAU Y      CAU H      AAU N      GAU D
    UAC Y      CAC H      AAC N      GAC D
    UAA Stop   CAA Q      AAA K      GAA E
    UAG Stop   CAG Q      AAG K      GAG E
    UGU C      CGU R      AGU S      GGU G
    UGC C      CGC R      AGC S      GGC G
    UGA Stop   CGA R      AGA R      GGA G
    UGG W      CGG R      AGG R      GGG G"""

    rna = []
    protienLetter = []
    split = protienCodes.split()
    for x, value in enumerate(split):
        if x % 2 == 0:
            rna.append(value)
        if x % 2 == 1:
            protienLetter.append(value)
    return rna, protienLetter

def numberOfRNAstrings(string):
    total = 3 #3 is for the stop codon
    rna, proteinLetters = getProtienCodes()
    for x in string:
        total = (proteinLetters.count(x)*total)%1000000 
    print (total)


string = "MVWWHSNCATLLQNQNTIHAYAGLGTPTTKKYVMGPGCGEFCESHIHFQAMGPMLKCITGWQFDWQERSEAQFDQYAMADQPGQRACWKEITCYYWVVRERCLQIWQQEANWEGREEAICTWPWQWGCYIYDKFWGMLCKRKEELINDFSGENKEFEQFAENHNLIDHNNMAWECHKFSMAFDCVSVFSLEGWPSDEVALAVNFPPLYFPACWRNMETLQAYCEWCTHEPQIIQIHTGNLWSHDTGVCVCYRHQHEGESAERQAKDSGTGWVVGVRAHKHKPIIEFRAAHGCAGPKCQPAKEQHACSVLCWGWVPQKVLGHGVKQTRWQNESHHTPWAEHKQPDIHQINISENSERTSTQIYKWLDYQCKDKSPMWDDVRRSKWVEIDHMQTMKWVCVMEHSHWLCQTNANRIPDRMNVVVQNVEYGTNTAHKLPNECVMIGNAWQELWPKVGEEPNGGLCRPETGQRSFMHQHMIGVDVNPCWSAPMLNFGKAIINVNSDQDHEQGICPPKLQLGFLHQAVIDVWDYHGCCTEYVWTHWQHQGCCTKKMKAEIYVYQSHNAIDETIILMETKRPFLFGTLLHYTRKYCHHNRELIDLHAWYRGPPGSHKYMPKFEHDHMPCFFHHNIHPDWIRKKKMLSFMDCALPVKKNRKGGMEHRMSILDAFHVLLQQHIVFFLNHCWKEQGCTRWIMKTNAQPDITISVAWVPYYCDNSKNTKDDFCHQHFVRPALRIWQKAPPLNMPNEAYNVNHDKDQMKTRQCETIIAFTMVVFYLIQTGERNFPIPRFYVQKVRDAITKSDQILSLNCRVQHHRMGFGPKNHESEIMPYWKLEALFNLMHMINKKQLPSKQQWHSWVYMRQGAYRWEEFKLREQPWCMSHISAQAWWEGPVMMRMAAALWMVGFWIRNYSRLTDAWHKRAITKDCGYPWVVRGGWVSTTAYNTHFFHTAFSGIVQSAGAREAMDHIGACWTCCEGFVREPPTDRGGTTTRWYPSTSWP"
numberOfRNAstrings(string)